### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by baart1989**
@akzhy let me know what you think

### CODE REVIEW

**Review by akzhy — CHANGES_REQUESTED** [review]
Hey, this is great thanks a lot. Just one change in the `contactFormSubmit` (https://github.com/akzhy/gatsby-starter-elemental/pull/30/files#diff-0bd249cf9ac7fc14e26c46da701972c3), you changed res.success to res.ok, while this might be suitable for most cases, the current API (getforms.io) returns an object with the success property, so it is better to keep it as it is, users using other APIs can change it themselves

**Comment by baart1989** [comment]
@akzhy sure that makes sense

Have done it, also added one small change to parallax component so it checks canUseDom property

**Comment by akzhy** [comment]
Hey, great work :) Merging it now.

**Comment by baart1989** [comment]
Thanks! 

Probably components could have little bit better types, but I think the most useful thing are auto-generated types for graphql queries.

I hope it will help progress with any further changes to project.

**Pull request merged**
