### PR TITLE
Add comments for blog posts

### LINKED ISSUE #14: Comment for blog post
### Problems

currently there is no way to add comments in a blog post, it would be nice to add that kind of feature. Since it maybe would attract more people to user's site, and also interactivity of the sites.

### Solution

Maybe we can add [this](https://www.gatsbyjs.org/packages/gatsby-plugin-disqus/) plugin so that there will be support for comments

Let me know what you think 😄

### PR DESCRIPTION
**Pull request by ahmad-reza619**
close #14 

i used the title as an id, i don't know if it's good or not 🤔 but i don't know about the id.

Also, i added new property inside gatsby-config.js . maybe i need to update readme?.

### CODE REVIEW

**Comment by akzhy** [comment]
Hey, @ahmad-reza619 sorry I've been busy these past days. This looks great, but I think we should enable the comments only if a Disqus shortname is given. I will look into this, and also, yes we need to update the readme file

**Comment by ahmad-reza619** [comment]
@akzhy Alright then, i'll include the logic to do so and update the readme

**Comment by ahmad-reza619** [comment]
i think i can implement this with checking siteUrl in siteMetadata, but apparently it can't be empty, i don't know why, i searched everywhere but don't find the answer. Also, i don't know how to determine if disqus shortname is given too 🤔 maybe put it in siteMetadata too so that it can be fetched via graphql? either way i need help with this @akzhy  😅

**Comment by akzhy** [comment]
Hey @ahmad-reza619 , thanks for the update. I am working on customizing the scheme so that a disqus field can be optionally added to the config file.

**Comment by akzhy** [comment]
Hey @ahmad-reza619 check #16

**Comment by ahmad-reza619** [comment]
nice change 😄 , then i'll close this one then

**Pull request closed without merging**
